# Generated by Django 5.2.15 on 2026-06-24 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_contrato', models.CharField(max_length=50, unique=True)),
                ('objeto', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('plazo_dias', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('ubicacion', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('registrado', 'Registrado'), ('activo', 'Activo'), ('en_cierre', 'En cierre'), ('cerrado', 'Cerrado')], default='registrado', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('avance_programado', models.PositiveSmallIntegerField(default=0)),
                ('avance_real', models.PositiveSmallIntegerField(default=0)),
                ('fecha_activacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=20)),
                ('representante', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'personas',
            },
        ),
        migrations.CreateModel(
            name='ConceptoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('unidad', models.CharField(max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('capitulo', models.CharField(blank=True, max_length=200)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_conceptos', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque', models.CharField(choices=[('contrato', 'Contrato Digitalizado'), ('catalogo', 'Catálogo de Conceptos'), ('programa', 'Programa de Obra'), ('juridico', 'Información Jurídica')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('formato', models.CharField(max_length=10)),
                ('tamano', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contracts.contract')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_termino', models.DateField()),
                ('motivo', models.CharField(max_length=300)),
                ('catalogo_snapshot', models.JSONField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='contracts.contract')),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contratista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contracts.contratista'),
        ),
        migrations.AddField(
            model_name='contract',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_residente', to='contracts.persona'),
        ),
        migrations.AddField(
            model_name='contract',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_supervisor', to='contracts.persona'),
        ),
        migrations.CreateModel(
            name='SolicitudActivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_activacion', to='contracts.contract')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_activacion_revisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_activacion_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
