# Generated by Django 5.2.15 on 2026-06-24 19:18

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdocument',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.contract_document_upload_to),
        ),
        migrations.AlterField(
            model_name='contractdocument',
            name='formato',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contractdocument',
            name='tamano',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
