# Generated by Django 5.2.15 on 2026-06-24 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contractdocument_archivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierta', models.BooleanField(default=False)),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
                ('nota_apertura', models.TextField(blank=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('instruccion', 'Instrucción'), ('respuesta', 'Respuesta'), ('acuerdo', 'Acuerdo'), ('observacion', 'Observación')], max_length=20)),
                ('contenido', models.TextField()),
                ('rol', models.CharField(choices=[('dependencia', 'Dependencia'), ('residente', 'Residente de Obra'), ('superintendente', 'Superintendente'), ('supervision', 'Supervisión'), ('finanzas', 'Finanzas')], max_length=20)),
                ('fecha', models.DateField()),
                ('firmas', models.JSONField(default=list)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_bitacora', to=settings.AUTH_USER_MODEL)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='contracts.bitacora')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
