# Generated by Django 5.2.15 on 2026-06-24 19:32

import contracts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_bitacora_bitacoranote'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraNoteFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=contracts.models.bitacora_foto_upload_to)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='contracts.bitacoranote')),
            ],
        ),
    ]
