# Generated by Django 5.2.15 on 2026-06-24 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_bitacoranotefoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('caratula', models.CharField(max_length=300)),
                ('numeros_generadores', models.CharField(blank=True, max_length=300)),
                ('registro_fotografico', models.PositiveIntegerField(default=0)),
                ('notas_soporte', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('en_revision', 'En revisión'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='en_revision', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('importe_bruto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amortizacion_anticipo', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('retencion_garantia', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('importe_neto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimaciones', to='contracts.contract')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contrato', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendida', 'Atendida')], default='pendiente', max_length=20)),
                ('fecha_atencion', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_pago', to='contracts.contract')),
                ('estimacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden_pago', to='contracts.estimacion')),
            ],
        ),
    ]
