# Generated by Django 5.2.15 on 2026-06-24 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_estimacion_ordenpago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdocument',
            name='bloque',
            field=models.CharField(choices=[('contrato', 'Contrato Digitalizado'), ('catalogo', 'Catálogo de Conceptos'), ('programa', 'Programa de Obra'), ('juridico', 'Información Jurídica'), ('garantia', 'Garantía')], max_length=20),
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cumplimiento', 'Cumplimiento'), ('anticipo', 'Anticipo'), ('vicios_ocultos', 'Vicios Ocultos')], max_length=20)),
                ('institucion_afianzadora', models.CharField(max_length=200)),
                ('numero_poliza', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_emision', models.DateField()),
                ('fecha_vigencia', models.DateField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_liberacion', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='contracts.contract')),
                ('documento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantia', to='contracts.contractdocument')),
                ('liberada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias_liberadas', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contrato', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Anticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_otorgado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('porcentaje_contrato', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_amortizacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_entrega', models.DateField()),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anticipo', to='contracts.contract')),
                ('garantia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anticipos', to='contracts.garantia')),
            ],
        ),
    ]
