# Generated by Django 5.2.15 on 2026-06-24 19:54

import contracts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contractdocument_bloque_garantia_anticipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plazo', 'Ampliación de Plazo'), ('monto', 'Modificación de Monto'), ('ambos', 'Plazo y Monto')], max_length=20)),
                ('justificacion', models.TextField()),
                ('monto_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dias_adicionales', models.PositiveIntegerField(default=0)),
                ('alcance', models.CharField(choices=[('ajuste_monto_simple', 'Ajuste de monto simple'), ('conceptos_nuevos', 'Conceptos nuevos'), ('ajuste_cantidades', 'Ajuste de cantidades')], max_length=30)),
                ('conceptos_afectados', models.JSONField(blank=True, null=True)),
                ('conceptos_nuevos', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='contracts.contract')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convenios_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConvenioDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=contracts.models.convenio_documento_upload_to)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contracts.convenio')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_convenio_subidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
