# Generated by Django 5.2.15 on 2026-06-24 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_convenio_conveniodocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('avance', 'Avance'), ('incidencia', 'Incidencia'), ('atraso', 'Atraso'), ('relevante', 'Situación Relevante')], max_length=20)),
                ('descripcion', models.TextField()),
                ('evidencia', models.CharField(blank=True, max_length=300)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_registrados', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='contracts.contract')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Incumplimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('atraso', 'Atraso'), ('calidad', 'Calidad'), ('seguridad', 'Seguridad')], max_length=20)),
                ('descripcion', models.TextField()),
                ('evidencia_ref', models.CharField(blank=True, max_length=300)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incumplimientos_registrados', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incumplimientos', to='contracts.contract')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('participantes', models.TextField(blank=True)),
                ('acuerdos', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('compromisos', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutas_registradas', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutas', to='contracts.contract')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceptos', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programa_obra', to='contracts.contract')),
            ],
        ),
    ]
