# Generated by Django 5.2 on 2026-07-01 17:49

import contracts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_cierre_finiquito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptocatalogo',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('terminado', 'Terminado')], default='en_proceso', max_length=20),
        ),
        migrations.AlterField(
            model_name='actaentregarecepcion',
            name='archivo',
            field=models.FileField(upload_to=contracts.models.acta_entrega_upload_to),
        ),
        migrations.CreateModel(
            name='ReporteAvanceConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('frente_ubicacion', models.CharField(max_length=200)),
                ('fotografia', models.ImageField(upload_to=contracts.models.reporte_avance_upload_to)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente de validación'), ('validado', 'Validado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_avance', to='contracts.conceptocatalogo')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_avance_creados', to=settings.AUTH_USER_MODEL)),
                ('reporte_anterior', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correccion', to='contracts.reporteavanceconcepto')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_avance_revisados', to=settings.AUTH_USER_MODEL)),
                ('usado_en_estimacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_consumidos', to='contracts.estimacion')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
