import type {
  Anticipo,
  AvanceDiario,
  Bitacora,
  Contract,
  Contratista,
  Convenio,
  Estimacion,
  Garantia,
  Incumplimiento,
  Minuta,
  OrdenPago,
  Persona,
  User,
} from "./types"

export const CONTRATISTAS: Contratista[] = [
  {
    id: "ct1",
    nombre: "ICA S.A.",
    rfc: "ICA840101AB1",
    representante: "Roberto Salinas",
    telefono: "55-1234-5678",
    correo: "contacto@ica.mx",
  },
  {
    id: "ct2",
    nombre: "Grupo Beta",
    rfc: "GBE920512XY9",
    representante: "Laura Méndez",
    telefono: "55-9876-5432",
    correo: "proyectos@grupobeta.mx",
  },
  {
    id: "ct3",
    nombre: "Electra MX",
    rfc: "EMX051120QW3",
    representante: "Jorge Vega",
    telefono: "55-4455-6677",
    correo: "obras@electramx.mx",
  },
  {
    id: "ct4",
    nombre: "Vías del Norte",
    rfc: "VNO110815RT5",
    representante: "Sofía Herrera",
    telefono: "55-2233-4455",
    correo: "contacto@viasdelnorte.mx",
  },
]

export const RESIDENTES: Persona[] = [
  {
    id: "r1",
    nombre: "Diego Ramírez",
    rfc: "RAGD850301HMC",
    telefono: "55-3001-1001",
    correo: "diego.ramirez@gacm.mx",
  },
  {
    id: "r2",
    nombre: "Mariana Flores",
    rfc: "FOMA880712MDF",
    telefono: "55-3001-1002",
    correo: "mariana.flores@gacm.mx",
  },
  {
    id: "r3",
    nombre: "Hugo Treviño",
    rfc: "TEVH790920HNL",
    telefono: "55-3001-1003",
    correo: "hugo.trevino@gacm.mx",
  },
]

export const SUPERVISORES: Persona[] = [
  {
    id: "s1",
    nombre: "Arturo Mendoza",
    rfc: "MEAA820505HDF",
    telefono: "55-4001-2001",
    correo: "arturo.mendoza@gacm.mx",
  },
  {
    id: "s2",
    nombre: "Patricia Núñez",
    rfc: "NUPP900218MDF",
    telefono: "55-4001-2002",
    correo: "patricia.nunez@gacm.mx",
  },
  {
    id: "s3",
    nombre: "Ricardo Salas",
    rfc: "SARR751130HJC",
    telefono: "55-4001-2003",
    correo: "ricardo.salas@gacm.mx",
  },
]

export const USERS: User[] = [
  // Dependencia
  {
    id: "u1",
    name: "Daniel Lopez",
    email: "dependencia@gacm.mx",
    password: "demo123",
    role: "dependencia",
    initials: "DL",
  },
  {
    id: "u1b",
    name: "Carmen Ríos",
    email: "dependencia2@gacm.mx",
    password: "demo123",
    role: "dependencia",
    initials: "CR",
  },
  // Residente de obra
  {
    id: "u2",
    name: "Diego Ramírez",
    email: "residente@gacm.mx",
    password: "demo123",
    role: "residente",
    initials: "DR",
    personaId: "r1",
  },
  {
    id: "u2b",
    name: "Mariana Flores",
    email: "residente2@gacm.mx",
    password: "demo123",
    role: "residente",
    initials: "MF",
    personaId: "r2",
  },
  {
    id: "u2c",
    name: "Hugo Treviño",
    email: "residente3@gacm.mx",
    password: "demo123",
    role: "residente",
    initials: "HT",
    personaId: "r3",
  },
  // Superintendente
  {
    id: "u3",
    name: "Víctor Castro",
    email: "superintendente@gacm.mx",
    password: "demo123",
    role: "superintendente",
    initials: "VC",
  },
  {
    id: "u3b",
    name: "Laura Sánchez",
    email: "superintendente2@gacm.mx",
    password: "demo123",
    role: "superintendente",
    initials: "LS",
  },
  // Supervisión
  {
    id: "u4",
    name: "Arturo Mendoza",
    email: "supervision@gacm.mx",
    password: "demo123",
    role: "supervision",
    initials: "AM",
  },
  {
    id: "u4b",
    name: "Patricia Núñez",
    email: "supervision2@gacm.mx",
    password: "demo123",
    role: "supervision",
    initials: "PN",
  },
  // Finanzas
  {
    id: "u5",
    name: "Dani Juárez",
    email: "finanzas@gacm.mx",
    password: "demo123",
    role: "finanzas",
    initials: "DJ",
  },
  {
    id: "u5b",
    name: "Roberto Ibáñez",
    email: "finanzas2@gacm.mx",
    password: "demo123",
    role: "finanzas",
    initials: "RI",
  },
]

export const CONTRACTS: Contract[] = [
  {
    id: "c1",
    noContrato: "GACM-2024-001",
    objeto: "Construcción Terminal 2 - Ampliación de instalaciones",
    descripcion:
      "Construcción de la Terminal 2 incluyendo áreas de abordaje, salas de espera y conexiones.",
    monto: 1200000,
    plazoDias: 365,
    fechaInicio: "2024-01-15",
    fechaTermino: "2025-01-14",
    ubicacion: "Zona Federal Aeroportuaria, Estado de México",
    contratista: CONTRATISTAS[0],
    residente: RESIDENTES[0],
    supervisor: SUPERVISORES[0],
    status: "activo",
    version: 1,
    avanceProgramado: 62,
    avanceReal: 58,
    // Cambio 1: sin documentos con bloque fianzas/garantias
    documentos: [
      {
        id: "d1",
        bloque: "contrato",
        nombre: "Contrato-GACM-2024-001.pdf",
        formato: "PDF",
        tamano: "2.4 MB",
        fecha: "2024-01-15",
        subidoPor: "Diego Ramírez",
      },
      {
        id: "d2",
        bloque: "catalogo",
        nombre: "Catalogo-Conceptos.xlsx",
        formato: "XLSX",
        tamano: "880 KB",
        fecha: "2024-01-16",
        subidoPor: "Diego Ramírez",
      },
      {
        id: "d3",
        bloque: "programa",
        nombre: "Programa-Obra.pdf",
        formato: "PDF",
        tamano: "1.1 MB",
        fecha: "2024-01-16",
        subidoPor: "Diego Ramírez",
      },
    ],
    catalogoConceptos: [
      {
        id: "cc1",
        clave: "CIM-001",
        descripcion: "Excavación a cielo abierto en material tipo II",
        unidad: "m³",
        cantidad: 1250,
        precioUnitario: 185.5,
        total: 231875,
      },
      {
        id: "cc2",
        clave: "CIM-002",
        descripcion: "Concreto f'c=250 kg/cm2 en cimentación",
        unidad: "m³",
        cantidad: 480,
        precioUnitario: 2750,
        total: 1320000,
      },
      {
        id: "cc3",
        clave: "EST-001",
        descripcion: "Acero de refuerzo fy=4200 kg/cm2",
        unidad: "ton",
        cantidad: 32.5,
        precioUnitario: 28500,
        total: 926250,
      },
    ],
    versiones: [
      {
        version: 1,
        fecha: "2024-01-15",
        monto: 1200000,
        fechaTermino: "2025-01-14",
        motivo: "Contrato original",
      },
    ],
  },
  {
    id: "c2",
    noContrato: "GACM-2024-002",
    objeto: "Remodelación Sala B - Modernización de espacios",
    descripcion: "Modernización integral de la Sala B de última espera.",
    monto: 450000,
    plazoDias: 180,
    fechaInicio: "2024-03-01",
    fechaTermino: "2024-08-28",
    ubicacion: "Terminal 1, Sala B",
    contratista: CONTRATISTAS[1],
    residente: RESIDENTES[0],
    supervisor: SUPERVISORES[1],
    status: "en_cierre",
    version: 2,
    avanceProgramado: 100,
    avanceReal: 96,
    documentos: [
      {
        id: "d5",
        bloque: "contrato",
        nombre: "Contrato-GACM-2024-002.pdf",
        formato: "PDF",
        tamano: "1.9 MB",
        fecha: "2024-03-01",
        subidoPor: "Diego Ramírez",
      },
      {
        id: "d6",
        bloque: "catalogo",
        nombre: "Catalogo-Conceptos-002.xlsx",
        formato: "XLSX",
        tamano: "560 KB",
        fecha: "2024-03-02",
        subidoPor: "Diego Ramírez",
      },
    ],
    catalogoConceptos: [],
    versiones: [
      {
        version: 1,
        fecha: "2024-03-01",
        monto: 420000,
        fechaTermino: "2024-07-29",
        motivo: "Contrato original",
      },
      {
        version: 2,
        fecha: "2024-06-10",
        monto: 450000,
        fechaTermino: "2024-08-28",
        motivo: "Convenio modificatorio: ampliación de plazo y monto",
      },
    ],
  },
  {
    id: "c3",
    noContrato: "GACM-2024-003",
    objeto: "Sistema eléctrico - Actualización de infraestructura",
    descripcion: "Actualización de subestaciones y tableros eléctricos.",
    monto: 820000,
    plazoDias: 240,
    fechaInicio: "2024-05-01",
    fechaTermino: "2024-12-27",
    ubicacion: "Subestación Central",
    contratista: CONTRATISTAS[2],
    residente: RESIDENTES[1],
    supervisor: SUPERVISORES[2],
    status: "registrado",
    version: 1,
    avanceProgramado: 0,
    avanceReal: 0,
    documentos: [
      {
        id: "d7",
        bloque: "contrato",
        nombre: "Contrato-GACM-2024-003.pdf",
        formato: "PDF",
        tamano: "2.1 MB",
        fecha: "2024-05-01",
        subidoPor: "Mariana Flores",
      },
    ],
    catalogoConceptos: [],
    versiones: [
      {
        version: 1,
        fecha: "2024-05-01",
        monto: 820000,
        fechaTermino: "2024-12-27",
        motivo: "Contrato original",
      },
    ],
  },
  {
    id: "c4",
    noContrato: "GACM-2024-004",
    objeto: "Pavimentación accesos - Rehabilitación de vialidades",
    descripcion: "Rehabilitación de vialidades y accesos vehiculares.",
    monto: 310000,
    plazoDias: 120,
    fechaInicio: "2024-02-10",
    fechaTermino: "2024-06-09",
    ubicacion: "Accesos Norte y Sur",
    contratista: CONTRATISTAS[3],
    residente: RESIDENTES[2],
    supervisor: SUPERVISORES[0],
    status: "activo",
    version: 1,
    avanceProgramado: 80,
    avanceReal: 71,
    documentos: [
      {
        id: "d8",
        bloque: "contrato",
        nombre: "Contrato-GACM-2024-004.pdf",
        formato: "PDF",
        tamano: "1.6 MB",
        fecha: "2024-02-10",
        subidoPor: "Hugo Treviño",
      },
      {
        id: "d9",
        bloque: "programa",
        nombre: "Programa-Obra-004.pdf",
        formato: "PDF",
        tamano: "900 KB",
        fecha: "2024-02-11",
        subidoPor: "Hugo Treviño",
      },
    ],
    catalogoConceptos: [],
    versiones: [
      {
        version: 1,
        fecha: "2024-02-10",
        monto: 310000,
        fechaTermino: "2024-06-09",
        motivo: "Contrato original",
      },
    ],
  },
]

export const BITACORAS: Bitacora[] = [
  {
    contratoId: "c1",
    abierta: true,
    fechaApertura: "2024-01-15",
    notaApertura:
      "Se apertura la bitácora de obra del contrato GACM-2024-001 conforme a la LOPySRM. Presentes el residente de obra y el superintendente.",
    notas: [
      {
        id: "bn1",
        numero: 1,
        tipo: "instruccion",
        contenido:
          "Se instruye al contratista a iniciar trabajos de cimentación conforme al programa de obra autorizado.",
        autor: "Diego Ramírez",
        rol: "residente",
        fecha: "2024-01-18",
        firmas: [
          { responsable: "Autor", nombre: "Diego Ramírez", firma: "D. Ramírez" },
          { responsable: "Superintendente", nombre: "Víctor Castro", firma: "V. Castro" },
          { responsable: "Supervisión", nombre: "Arturo Mendoza", firma: "A. Mendoza" },
        ],
      },
      {
        id: "bn2",
        numero: 2,
        tipo: "respuesta",
        contenido:
          "El superintendente confirma el inicio de trabajos de cimentación con el frente 1.",
        autor: "Víctor Castro",
        rol: "superintendente",
        fecha: "2024-01-19",
        firmas: [
          { responsable: "Autor", nombre: "Víctor Castro", firma: "V. Castro" },
          { responsable: "Residente de Obra", nombre: "Diego Ramírez", firma: "D. Ramírez" },
          { responsable: "Supervisión", nombre: "Arturo Mendoza", firma: "A. Mendoza" },
        ],
      },
      {
        id: "bn3",
        numero: 3,
        tipo: "observacion",
        contenido:
          "La supervisión observa que el acero de refuerzo cumple con las especificaciones del proyecto.",
        autor: "Arturo Mendoza",
        rol: "supervision",
        fecha: "2024-01-25",
        firmas: [
          { responsable: "Autor", nombre: "Arturo Mendoza", firma: "A. Mendoza" },
          { responsable: "Residente de Obra", nombre: "Diego Ramírez", firma: "D. Ramírez" },
          { responsable: "Superintendente", nombre: "Víctor Castro", firma: "V. Castro" },
        ],
      },
    ],
  },
  {
    contratoId: "c2",
    abierta: true,
    fechaApertura: "2024-03-01",
    notaApertura:
      "Se apertura la bitácora de obra del contrato GACM-2024-002 conforme a la LOPySRM.",
    notas: [
      {
        id: "bn4",
        numero: 1,
        tipo: "acuerdo",
        contenido:
          "Se acuerda con el contratista el horario de trabajos nocturnos para no afectar operaciones.",
        autor: "Diego Ramírez",
        rol: "residente",
        fecha: "2024-03-05",
        firmas: [
          { responsable: "Autor", nombre: "Diego Ramírez", firma: "D. Ramírez" },
          { responsable: "Superintendente", nombre: "Laura Sánchez", firma: "L. Sánchez" },
          { responsable: "Supervisión", nombre: "Patricia Núñez", firma: "P. Núñez" },
        ],
      },
    ],
  },
  {
    contratoId: "c4",
    abierta: true,
    fechaApertura: "2024-02-10",
    notaApertura: "Se apertura la bitácora de obra del contrato GACM-2024-004.",
    notas: [],
  },
]

// ── Cambio 2: Estimaciones con desglose financiero ────────────────────────────
// importeBruto = monto original, amortizacion=5%, retencion=5%, iva=16% sobre base gravable
export const ESTIMACIONES: Estimacion[] = [
  {
    id: "e1",
    contratoId: "c1",
    numero: 1,
    periodoInicio: "2024-01-15",
    periodoFin: "2024-02-15",
    importeBruto: 180000,
    amortizacionAnticipo: 9000,   // 5% del bruto (anticipo 20% del contrato, amort 5%)
    retencionGarantia: 9000,       // 5%
    iva: 25920,                    // (180000-9000-9000)*0.16
    importeNeto: 187920,
    caratula: "Estimación 1 - Trabajos de cimentación",
    numerosGeneradores: "Volúmenes de excavación y concreto f'c=250",
    registroFotografico: 12,
    notasSoporte: 3,
    status: "aceptada",
    observaciones: "Revisada y validada sin observaciones.",
    creadaPor: "Víctor Castro",
    fechaCreacion: "2024-02-16",
  },
  {
    id: "e2",
    contratoId: "c1",
    numero: 2,
    periodoInicio: "2024-02-16",
    periodoFin: "2024-03-15",
    importeBruto: 240000,
    amortizacionAnticipo: 12000,
    retencionGarantia: 12000,
    iva: 34560,
    importeNeto: 250560,
    caratula: "Estimación 2 - Estructura nivel 1",
    numerosGeneradores: "Acero de refuerzo y cimbra",
    registroFotografico: 18,
    notasSoporte: 4,
    status: "aceptada",
    observaciones: "Aprobada.",
    creadaPor: "Víctor Castro",
    fechaCreacion: "2024-03-16",
  },
  {
    id: "e3",
    contratoId: "c1",
    numero: 3,
    periodoInicio: "2024-03-16",
    periodoFin: "2024-04-15",
    importeBruto: 280000,
    amortizacionAnticipo: 14000,
    retencionGarantia: 14000,
    iva: 40320,
    importeNeto: 292320,
    caratula: "Estimación 3 - Estructura nivel 2",
    numerosGeneradores: "Losas y columnas nivel 2",
    registroFotografico: 15,
    notasSoporte: 2,
    status: "en_revision",
    observaciones: "",
    creadaPor: "Víctor Castro",
    fechaCreacion: "2024-04-16",
  },
  {
    id: "e4",
    contratoId: "c4",
    numero: 1,
    periodoInicio: "2024-02-10",
    periodoFin: "2024-03-10",
    importeBruto: 120000,
    amortizacionAnticipo: 6000,
    retencionGarantia: 6000,
    iva: 17280,
    importeNeto: 125280,
    caratula: "Estimación 1 - Terracerías",
    numerosGeneradores: "Movimiento de tierras y compactación",
    registroFotografico: 8,
    notasSoporte: 2,
    status: "aceptada",
    observaciones: "Aprobada.",
    creadaPor: "Víctor Castro",
    fechaCreacion: "2024-03-11",
  },
]

// ── Cambio 5: Convenios con alcance ───────────────────────────────────────────
export const CONVENIOS: Convenio[] = [
  {
    id: "cv1",
    contratoId: "c2",
    tipo: "ambos",
    justificacion:
      "Se requiere ampliación de plazo y monto debido a trabajos extraordinarios solicitados para la modernización de instalaciones eléctricas no contempladas originalmente.",
    montoAdicional: 30000,
    diasAdicionales: 30,
    documentos: 3,
    status: "aprobado",
    motivoRechazo: "",
    solicitadoPor: "Víctor Castro",
    fechaSolicitud: "2024-06-01",
    alcance: "ajuste_monto_simple",
  },
  {
    id: "cv2",
    contratoId: "c1",
    tipo: "plazo",
    justificacion:
      "Solicitud de ampliación de plazo por condiciones climáticas adversas que retrasaron los trabajos de cimentación.",
    montoAdicional: 0,
    diasAdicionales: 20,
    documentos: 2,
    status: "pendiente",
    motivoRechazo: "",
    solicitadoPor: "Diego Ramírez",
    fechaSolicitud: "2024-04-20",
    alcance: "ajuste_monto_simple",
  },
]

export const ORDENES_PAGO: OrdenPago[] = [
  {
    id: "op1",
    contratoId: "c1",
    noContrato: "GACM-2024-001",
    estimacionId: "e1",
    estimacionNumero: 1,
    monto: 187920,
    fechaEmision: "2024-02-17",
    status: "atendida",
    fechaAtencion: "2024-02-22",
  },
  {
    id: "op2",
    contratoId: "c1",
    noContrato: "GACM-2024-001",
    estimacionId: "e2",
    estimacionNumero: 2,
    monto: 250560,
    fechaEmision: "2024-03-17",
    status: "pendiente",
    fechaAtencion: null,
  },
  {
    id: "op3",
    contratoId: "c4",
    noContrato: "GACM-2024-004",
    estimacionId: "e4",
    estimacionNumero: 1,
    monto: 125280,
    fechaEmision: "2024-03-12",
    status: "pendiente",
    fechaAtencion: null,
  },
]

export const AVANCES: AvanceDiario[] = [
  {
    id: "a1",
    contratoId: "c1",
    tipo: "avance",
    descripcion: "Colado de losa de entrepiso nivel 1 completado al 100%.",
    evidencia: "foto-losa-n1.jpg",
    autor: "Arturo Mendoza",
    fecha: "2024-03-20",
  },
  {
    id: "a2",
    contratoId: "c1",
    tipo: "atraso",
    descripcion:
      "Retraso de 2 días en suministro de acero por parte del proveedor.",
    evidencia: "",
    autor: "Arturo Mendoza",
    fecha: "2024-03-22",
  },
  {
    id: "a3",
    contratoId: "c4",
    tipo: "incidencia",
    descripcion: "Lluvia detuvo trabajos de pavimentación durante la mañana.",
    evidencia: "",
    autor: "Patricia Núñez",
    fecha: "2024-04-02",
  },
]

export const INCUMPLIMIENTOS: Incumplimiento[] = [
  {
    id: "i1",
    contratoId: "c4",
    tipo: "atraso",
    descripcion:
      "Atraso acumulado de 9 puntos porcentuales respecto al programa de obra autorizado.",
    evidenciaRef: "Registro diario del 02/04/2024 y curva S",
    autor: "Hugo Treviño",
    fecha: "2024-04-05",
  },
]

export const MINUTAS: Minuta[] = [
  {
    id: "m1",
    contratoId: "c1",
    titulo: "Reunión semanal de seguimiento - Semana 12",
    participantes: "Diego Ramírez, Víctor Castro, Arturo Mendoza",
    acuerdos:
      "Acelerar suministro de acero. Reprogramar frente 2 para recuperar atraso.",
    observaciones: "Se detecta atraso menor recuperable en próximas 2 semanas.",
    compromisos: "Contratista entregará programa de recuperación el 25/03.",
    autor: "Diego Ramírez",
    fecha: "2024-03-21",
  },
]

// ── Cambio 1: Garantías con modelo extendido ──────────────────────────────────
export const GARANTIAS: Garantia[] = [
  {
    id: "g1",
    contratoId: "c1",
    tipo: "cumplimiento",
    institucionAfianzadora: "Afianzadora Insurgentes S.A.",
    numeroPoliza: "AI-2024-00123",
    monto: 120000,
    fechaEmision: "2024-01-15",
    fechaVigencia: "2026-01-15",
    status: "vigente",
    documento: null,
    registradoPor: "Diego Ramírez",
    fechaRegistro: "2024-01-15",
  },
  {
    id: "g2",
    contratoId: "c1",
    tipo: "anticipo",
    institucionAfianzadora: "Afianzadora Insurgentes S.A.",
    numeroPoliza: "AI-2024-00124",
    monto: 240000,
    fechaEmision: "2024-01-16",
    fechaVigencia: "2025-01-16",
    status: "vigente",
    documento: null,
    registradoPor: "Diego Ramírez",
    fechaRegistro: "2024-01-16",
  },
  {
    id: "g3",
    contratoId: "c2",
    tipo: "cumplimiento",
    institucionAfianzadora: "Fianzas Monterrey Nueva York S.A.",
    numeroPoliza: "FMN-2024-00456",
    monto: 45000,
    fechaEmision: "2024-03-01",
    fechaVigencia: "2024-09-01",
    status: "vencida",
    documento: null,
    registradoPor: "Diego Ramírez",
    fechaRegistro: "2024-03-01",
  },
]

// ── Cambio 2: Anticipos ───────────────────────────────────────────────────────
export const ANTICIPOS: Anticipo[] = [
  {
    id: "ant1",
    contratoId: "c1",
    montoOtorgado: 240000,        // 20% del contrato de $1,200,000
    porcentajeContrato: 20,
    porcentajeAmortizacion: 5,    // amortiza 5% del bruto de cada estimación
    fechaEntrega: "2024-01-20",
    saldoPendiente: 219000,        // 240000 - 9000(e1) - 12000(e2) = 219000 (ya amortizadas las aceptadas)
    garantiaId: "g2",
  },
  {
    id: "ant2",
    contratoId: "c4",
    montoOtorgado: 62000,          // 20% de $310,000
    porcentajeContrato: 20,
    porcentajeAmortizacion: 5,
    fechaEntrega: "2024-02-15",
    saldoPendiente: 56000,          // 62000 - 6000(e4)
    garantiaId: "",
  },
]
