# Generated by Django 5.2.15 on 2026-06-24 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='persona_id',
        ),
        migrations.AddField(
            model_name='user',
            name='persona',
            field=models.ForeignKey(blank=True, help_text='Vincula esta cuenta a una Persona (residente, supervisor o superintendente) para controlar a qué contratos tiene acceso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='contracts.persona'),
        ),
    ]
